deploy:
  image:
    name: alpine/k8s:1.27.1
  script:
    - docker build vote -t 13.229.237.230:30001/voting-app/vote
    - docker build result -t 13.229.237.230:30001/voting-app/result
    - docker build worker -t 13.229.237.230:30001/voting-app/worker
    - docker build seed-data -t 13.229.237.230:30001/voting-app/seed-data