deploy:
  image:
    name: alpine/k8s:1.27.1
  before_script:
    - kubectl delete -f k8s-specifications/ --namespace voting-app
  script:
    - kubectl create namespace voting-app
    - kubectl create -f k8s-specifications/ --namespace voting-app
  when: always