build-and-deploy:
  image: alpine/k8s:1.27.1
  script:
    - kubectl apply -f k8s-specifications/ -n voting-app

build:
  image:
    name: moby/buildkit
    entrypoint:
      - buildctl-daemonless.sh
  script:
    - buildctl --addr tcp://127.0.0.1:1234 build --frontend=dockerfile.v0 --local context=vote --local dockerfile=vote
    - docker build result -t 13.229.237.230:30001/voting-app/result
    - docker build worker -t 13.229.237.230:30001/voting-app/worker
    - docker build seed-data -t 13.229.237.230:30001/voting-app/seed-data